config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :checks

  resources :pins
  resources :checkboxes

  devise_for :users
  match 'users/:id' => 'users#show', :via => [:get],  as: :user
  root "pins#index"
  get "about" => "pages#about"
  get "profile" => "pins#profile"

  

end

app/models/check.rb
class Check < ActiveRecord::Base
	belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_many :checks
 
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

     #forces user to upload
     #validates :image, presence: true
     validates :title, presence: true
     validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  



  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]
  before_action :set_pin

  respond_to :html

  def index
    @checks = Check.all
    respond_with(@checks)
  end

  def show
    respond_with(@check)
  end

  def new
    @check = Check.new
    respond_with(@check)
  end

  def edit
  end

  def create
    @check = Check.new(check_params)
    @check.pin_id = @pin.id
    @check.save
    respond_with(@check)
  end

  def update
    @check.update(check_params)
    respond_with(@check)
  end

  def destroy
    @check.destroy
    respond_with(@check)
  end

  private
    def set_check
      @check = Check.find(params[:id])
    end

    def check_params
      params.require(:check).permit(:pin_id, :check)
    end

     def set_pin
      @pin = Pin.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :update_pin, only: [:show]
  
 
  


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page])
  end


    def profile
      @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page])
  end

  def show
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page])
  end

  def new
    @pin = current_user.pins.build
    
    

  end

  def edit
  end

  def create
 
    #If it was created already will go to else statement, if first time being created will display 'pin was succ...'



    
   @pin = current_user.pins.build(pin_params)

   
  

    #If it was created already will go to else statement, if first time being created will display 'pin was succ...'
    if @pin.save

      # tempNum = 0

      # while tempNum < 30

      #   @check = Check.create

      #   tempNum = tempNum + 1

      # end

      redirect_to @pin, notice: 'Goal was successfully created.'

    else
      render action: 'new'
    end
  end

  def update


    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Goal was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def update_pin
      @pin = Pin.find(params[:id])
    end 

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this Goal" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :title, :completed)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
    @user = User.find(params[:id])
    @pins = Pin.where(:user_id => params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checks/_form.html.erb
<%= form_for(@check) do |f| %>
  <% if @check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check.errors.count, "error") %> prohibited this check from being saved:</h2>

      <ul>
      <% @check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :check %><br>
    <%= f.check_box :check %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<h1>Listing checks</h1>

<table>
  <thead>
    <tr>
      <th>Pin</th>
      <th>Check</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= check.pin_id %></td>
        <td><%= check.check %></td>
        <td><%= link_to 'Show', check %></td>
        <td><%= link_to 'Edit', edit_check_path(check) %></td>
        <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1>New check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pin:</strong>
  <%= @check.pin_id %>
</p>

<p>
  <strong>Check:</strong>
  <%= @check.check %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->

  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "One Month Goals", root_path, class:"navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        

        <% if user_signed_in? %>
          <li> <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus-sign"></span> New goal
            <% end %> 
          </li>
          <li><%= link_to "My Goals", profile_path %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li> 
        <% else %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li> 
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Month Goals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>

</head>
<body>

<%= render 'layouts/header'%>


<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron center">
        <h2>Welcome to One Month Goals</h2>
       	<p>Change your life by creating one month long goals.</p>
         <p>
           <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>

           <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         </p>
    	<% end %>  
  </div>

app/views/pages/about.html.erb
<h1> About Page </h1>
<p>We are working on the site currently. Will update soon!</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
    
     <% if user_signed_in? %>
      <h3>Currently working on site, however, click link below to get started if you are feeling crazy!</h3>
          <%= link_to "List One Month Goals", pins_path, class: "btn btn-primary btn-lg" %>
     <% else %>
      <h2>Welcome to One Month Goals</h2>
     	<p>Change your life by creating one month long goals.</p>
       <p>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>

         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         
       </p>


  	<% end %>  

</div>

app/views/pins/_form.html.erb
<%= form_for(@pin, html: {multipart:true}) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- For image uploads
<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

-->

  <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: "form-control" %>
     </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Goal", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_showForm.html.erb
<%= form_for(@pin, html: {multipart:true}) do |f| %>

  <!-- Displays error if needed -->
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Checkbox, auto decides whether to be showcasing checked or not thanks to rails -->
  <!-- This code also does if check to see if user can update checkbox or not -->
  <div class="form-group">
    <%= f.label "Completed:" %>
    <% if user_signed_in? %>
      <% if @pin.user_id == current_user.id %>
        <%= f.check_box :completed, :disabled => false %>
      <% else %>
        <%= f.check_box :completed, :disabled => true %>
      <% end %>
    <% else %>
      <%= f.check_box :completed, :disabled => true %>
    <% end %>
  </div>

  <!-- Showcase save button depending on if it's that users goal -->
  <% if user_signed_in? %>
    <% if @pin.user_id == current_user.id %>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'View', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<!-- <li><%= link_to "Profile", current_user %></li> -->
<%= render 'pages/home' =%>


<div id="pins" class="transitions-enabled">


  
    <% @pins.each do |pin| %>
      
        <div class="box panel panel-default"> 

        <%= link_to(pin) do %>
          <div class="panel-body">
            
            
            <!-- used to not allow titles and was just descriptions -->
          <% if pin.title.nil? %>
            <p><%= pin.description %></p>
          <% else %>
            <p><%= pin.title %></p>

          <% end %>
          <p><strong><%= pin.user.name if pin.user %></strong>
         <% if pin.user != current_user %>

         



         <% end %>
          
            
           

            
          </div><!-- end div panel-body -->
        
        
        </div><!-- end div box panel panel-default -->
        <% end %>
   
  <% end %>
</div><!-- end main div -->

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/profile.html.erb
	<h3> Your Goals </h3>



<div id="pins" class="transitions-enabled">


  
    <% @pins.each do |pin| %>

    <% if pin.user == current_user %>




      <div class="box panel panel-default">

        <div class="panel-body">
          <%= link_to content_tag(pin.description), pin %>
          <p><%= pin.description %></p>
          <p><strong><%= pin.user.name if pin.user %></strong>
         <% if pin.user != current_user %>
         <p> <%= link_to "View", pin %></p>
         <% end %>

          <% if pin.user == current_user %>

             <div class="actions">

              <%= link_to "View", pin %>


             	

                <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
              <% end %>
                <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
                Delete
              <% end %>
            </div>
          <% end %>
        
        </div>
      </div>
     <% end %>  
    <% end %> <!-- End loop -->
  </div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">

				<!-- Some users didn't enter at start -->
				<% if @pin.title.nil? %>
					Goal

				<% else %>
					<%= @pin.title %>
				<% end %>
			</div>
			<div class="panel-body">

				<p>
				  <strong>Description:</strong>
				  <%= @pin.description %>
				  
				  <p><strong> By: </strong> <%= link_to @pin.user.name,  @pin.user if @pin.user%></p>
				</p>

				<p>Created <%= time_ago_in_words(@pin.created_at) %> ago</p>

				<!-- 
				<% if @pin_user == current_user %>
					 <%= link_to edit_pin_path(@pin) do %>
        			<span class="glyphicon glyphicon-edit"></span>
       					 Edit
      				<% end %>
				<% end %>
			-->
			</div>
		</div>
	</div> <!-- End of first "row" -->

	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		

			<div class="panel-body">
				<%= render 'showForm.html.erb' %>

			</div> 
		</div>
	</div> <!-- End of second "row" -->			
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Goals:</h1><br>

<div id="pins" class="transitions-enabled">

	<% @pins.each do |pin| %>
		
		<div class="box panel panel-default"> 
	        <%= link_to(pin) do %>
	          <div class="panel-body">
	            
	            
	            <!-- used to not allow titles and was just descriptions -->
	          <% if pin.title.nil? %>
	            <p><%= pin.description %></p>
	          <% else %>
	            <p><%= pin.title %></p>

	          <% end %>
	          <p><strong><%= pin.user.name if pin.user %></strong>
	         <% if pin.user != current_user %>

	         



	         <% end %>
	          
	            
	           

	            
	          </div><!-- end div panel-body -->
	        
	        
	        </div><!-- end div box panel panel-default -->
	        <% end %>

	<% end %>
</div>